### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by collinanderson** [Atomidata/django-audit-log#17]
It looks like this project wouldn't take much work to get python 3 support. I think the models.pyfile just needs `from __future__ import unicode_literals`, and the `__unicode__` reference would need to be `__str__` on python 3.

**Comment by vvangelovski** [comment]
If you checkout the latest version from github it should work with python 3, but I have to do some more testing and some other changes to make a pypi release compatible with python 3.

**Comment by vvangelovski** [comment]
Python 3 support is now added in version 0.6.0. Please let me know if you have any problems with it.

:+1:
