### ISSUE TITLE
How to get log_entry.action_date value

### ISSUE THREAD

**Issue by vaibhav-jain** [Atomidata/django-audit-log#18]
I need to access `log_entry.action_date` value.
Right now I can access `<Customer: XXXX deleted at 2015-01-17 19:09:48.515000+00:00>` But how do I render this `string` into `datetime` value in template????? Is their way of getting access to `log_entry.action_date`??

**Comment by vvangelovski** [comment]
log_entry.action_date gives you the datetime of the action.

**Comment by vaibhav-jain** [comment]
Yeah but how do i access it using manager???

**Comment by vaibhav-jain** [comment]
I need to show action datetime in templates in user specific time format.

**Comment by vaibhav-jain** [comment]
Can you please tell me that should I use `TimeStampedModel from django-extensions` along with `audit-log`

**Comment by vvangelovski** [comment]
You can use TimeStampedModel from django-extensions on any model if you want to. Don't confuse it with AuthStampedModel from django-audit-log.

To get the datetime of a certain action you need to get an instance of the log entry for that action. You can't get it from the manager.

In the example that you gave log_entry.action_date will give you the datetime for that log_entry, it's not a string it's a datetime.

**Comment by vaibhav-jain** [comment]
Thanks for your help. It was all my mistake. 
`self.audit_log.filter().order_by('-action_date')[0]` . I forgot `.action_date` in the query `self.audit_log.filter().order_by('-action_date')[0].action_date`.  So sorry
